### ISSUE TITLE
Incorrect processing 0 decimals parameter

### ISSUE THREAD

**Issue by ycherniavskyi** [sainf/vue-filter-pretty-bytes#3]
Current condition
https://github.com/sainf/vue-filter-pretty-bytes/blob/457416fb759c301e7eabf832832afe4adecfcbdc/vue-filter-pretty-bytes.js#L20
must be replaced with
```js
const dm = decimals != null ? decimals : 2
```

**Comment by sainf** [comment]
Thank's for notice!
